# Generated by Django 6.0 on 2026-01-06 09:10

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aez_zone',
            fields=[
                ('aez_id', models.IntegerField(primary_key=True, serialize=False)),
                ('zone_name', models.CharField(blank=True, max_length=100, null=True)),
                ('altitude_range', models.CharField(blank=True, max_length=100, null=True)),
                ('average_annual_rainfall', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LivestockCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PastureCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SoilType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('ph_range', models.CharField(blank=True, max_length=20)),
                ('texture', models.CharField(blank=True, max_length=50)),
                ('drainage', models.CharField(blank=True, max_length=50)),
                ('fertility', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(blank=True, max_length=500, null=True)),
                ('last_name', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('user', 'Regular User')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('crop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='CropRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_rainfall', models.IntegerField(null=True)),
                ('max_rainfall', models.IntegerField(null=True)),
                ('min_temp', models.IntegerField(null=True)),
                ('max_temp', models.IntegerField(null=True)),
                ('min_altitude', models.IntegerField(null=True)),
                ('max_altitude', models.IntegerField(null=True)),
                ('drought_tolerance', models.CharField(blank=True, max_length=20)),
                ('flood_tolerance', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='api.crop')),
            ],
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('maturity_days', models.IntegerField(null=True)),
                ('min_altitude', models.IntegerField(null=True)),
                ('max_altitude', models.IntegerField(null=True)),
                ('yield_potential', models.CharField(blank=True, max_length=50)),
                ('drought_tolerance', models.CharField(blank=True, max_length=20)),
                ('release_year', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='api.crop')),
            ],
        ),
        migrations.CreateModel(
            name='Livestock',
            fields=[
                ('livestock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('breed', models.CharField(blank=True, max_length=50)),
                ('aez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestocks', to='api.aez_zone')),
                ('livestockcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestocks', to='api.livestockcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Pasture',
            fields=[
                ('pasture_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pasturecategory')),
            ],
        ),
        migrations.CreateModel(
            name='PastureVariety',
            fields=[
                ('variety_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('aez', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastures', to='api.aez_zone')),
                ('pasture_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pasture')),
            ],
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('subcounty_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='api.county')),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('ward_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('altitude', models.IntegerField(null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('soil_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
                ('subcounty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='api.subcounty')),
            ],
        ),
    ]
