# Generated by Django 6.0 on 2026-01-06 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ward_annual_rain_ward_annual_temp_ward_ke_elev_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soil_type', models.CharField(max_length=100)),
                ('drainage', models.CharField(max_length=50)),
                ('depth_or_texture', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='cropvariety',
            old_name='name',
            new_name='variety',
        ),
        migrations.RemoveField(
            model_name='cropvariety',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cropvariety',
            name='drought_tolerance',
        ),
        migrations.RemoveField(
            model_name='cropvariety',
            name='maturity_days',
        ),
        migrations.RemoveField(
            model_name='cropvariety',
            name='max_altitude',
        ),
        migrations.RemoveField(
            model_name='cropvariety',
            name='min_altitude',
        ),
        migrations.RemoveField(
            model_name='cropvariety',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='cropvariety',
            name='yield_potential',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='soil_type',
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='availability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='drought_tolerant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='farmer_preference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='maxAlti',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='maxPrep',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='maxTemp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='maxpH',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='minAlti',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='minPrep',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='minTemp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='minpH',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='pest_tolerant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='soil_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='varieties', to='api.soilcondition'),
        ),
        migrations.DeleteModel(
            name='CropRequirement',
        ),
    ]
