# Generated by Django 6.0 on 2026-01-06 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_soilcondition_rename_name_cropvariety_variety_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropvariety',
            name='soil_condition',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='soiltype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='soiltype',
            name='drainage',
        ),
        migrations.RemoveField(
            model_name='soiltype',
            name='fertility',
        ),
        migrations.RemoveField(
            model_name='soiltype',
            name='ph_range',
        ),
        migrations.RemoveField(
            model_name='soiltype',
            name='texture',
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_en_sw',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='crop_scientificname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CropSoiltype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cropvariety')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.soiltype')),
            ],
        ),
        migrations.DeleteModel(
            name='SoilCondition',
        ),
    ]
