# Generated by Django 6.0 on 2026-01-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cropvariety_soil_condition_remove_crop_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcounty',
            name='subcounty_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
