# Generated by Django 6.0 on 2026-01-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_subcounty_subcounty_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcounty',
            old_name='name',
            new_name='subcounty_name',
        ),
    ]
