# Generated by Django 6.0 on 2026-01-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_name_subcounty_subcounty_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='county',
            old_name='name',
            new_name='county_name',
        ),
        migrations.RenameField(
            model_name='ward',
            old_name='name',
            new_name='ward_name',
        ),
    ]
