# Generated by Django 6.0 on 2026-01-06 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcounty',
            name='subcounty_code',
        ),
    ]
