# Generated by Django 6.0 on 2026-01-07 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_subcounty_subcounty_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ward',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='annual_rain',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='annual_temp',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='ke_elev',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='ke_ph',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='lr_rain',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='lr_temp',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='sr_rain',
        ),
        migrations.RemoveField(
            model_name='ward',
            name='sr_temp',
        ),
        migrations.AddField(
            model_name='ward',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.county'),
        ),
        migrations.CreateModel(
            name='Warddetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('altitude', models.IntegerField(null=True)),
                ('annual_rain', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('annual_temp', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('ke_elev', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('ke_ph', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('lr_rain', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('lr_temp', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('sr_rain', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('sr_temp', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wardsdata', to='api.ward')),
            ],
        ),
    ]
