# Generated by Django 6.0 on 2026-01-07 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_ward_altitude_remove_ward_annual_rain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='county',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='api.county'),
        ),
    ]
