# Generated by Django 4.2.11 on 2026-01-09 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Market Type',
                'verbose_name_plural': 'Market Types',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='aez_zone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='aez_zone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='county',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='maintainer_seed_source',
            field=models.CharField(blank=True, help_text='Seed source or maintaining institution', max_length=250),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='maturity_duration_max_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='maturity_duration_min_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='owner',
            field=models.CharField(blank=True, help_text='Institution or breeder owning the variety', max_length=250),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='release_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Year the variety was released', null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='special_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='yield_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='yield_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cropvariety',
            name='yield_unit',
            field=models.CharField(default='t/ha', help_text='Yield unit e.g. t/ha, kg/acre', max_length=50),
        ),
        migrations.AddField(
            model_name='livestock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='disease_resistance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='feed_requirements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='prod_system',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='livestock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='livestockcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pasture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pasture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pasturecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pasturecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pasturevariety',
            name='biomass_production',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pasturevariety',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='pasturevariety',
            name='persistence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='pasturevariety',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pasturevariety',
            name='water_requirements',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='soiltype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subcounty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='ward',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='warddetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='county_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='crop',
            name='crop_name_en',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcounty',
            name='subcounty_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ward',
            name='ward_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='warddetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='DailyMarketPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('altitude_mode', models.PositiveSmallIntegerField(default=0)),
                ('tessellate', models.BooleanField(default=False)),
                ('extrude', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=True)),
                ('draw_order', models.PositiveSmallIntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate', max_digits=9)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='market_icons/')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='api.county')),
                ('market_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='api.markettype')),
            ],
            options={
                'verbose_name': 'Daily Market Priority',
                'verbose_name_plural': 'Daily Market Priorities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['county'], name='api_dailyma_county__1687c6_idx'), models.Index(fields=['market_type'], name='api_dailyma_market__352dcb_idx'), models.Index(fields=['start_time', 'end_time'], name='api_dailyma_start_t_5afb37_idx')],
            },
        ),
    ]
